version: "3"
services:
  db:
    image: mysql:5.7
    env_file: ./mysql/mysql.env
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d/:ro
      - mysqldata:/var/lib/mysql
    networks:
      - backend

  app:
    image: node:16
    environment:
      - TZ=Asia/Tokyo
    tty: true
    ports: # Host port:Container port
      - "5001:5001"
      - "8000:8000"
    volumes:
      - ./app:/app
    working_dir: /app
    #    command: npm run dev  ## create-frourio-appが完了するまでコメントアウト。
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  mysqldata:
